language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.2
  - jruby-1.7.23
  - jruby-9.0.5.0

services:
  - mongodb

sudo: false

bundler_args: --without development

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
