language: ruby
bundler_args: --without development
rvm:
  - 2.0
  - 2.2
  - jruby-1.7
  - jruby-9
services:
  - mongodb
sudo: false

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
